import { layoutTypes } from './data.js?v=0.7.0';
import { icon } from './icons.js';

const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));

export const expressions = [
  { id: 'welcome-path', title: 'A Place to Contribute', eyebrow: 'Invitation · living work', description: 'Alice’s invitation opens a coherent path into Service Alliance work without requiring a commitment.', layout: 'composed', realm: 'Service Alliance', source: 'Alice', privacy: 'Private', access: 'Invitation-scoped', recent: 7, saved: true, parts: ['Service Alliance Realm', 'Kinship Map', 'Invitation Seed', 'Alice Transmitter'], image: 'assets/sigils/invitation.png', why: 'A direct relationship and active invitation make this relevant now.' },
  { id: 'build-room', title: 'Build Kiduna Working Room', eyebrow: 'Spatial collaboration', description: 'An isometric room for current releases, decisions, contributors, and tools.', layout: 'setting', realm: 'Build Kiduna', source: 'Moto', privacy: 'Private', access: 'Realm members', recent: 6, saved: true, parts: ['Build Kiduna Realm', 'Contribution Map', 'Layout Seed'], image: 'assets/sigils/alliance.png', why: 'You have current work and two decisions in this Realm.' },
  { id: 'signal-weather', title: 'Signals Near the Welcome Path', eyebrow: 'Layered Field view', description: 'A Pulse of invitations, care thresholds, decisions, and available support around one Locus.', layout: 'pulse', realm: 'Service Alliance', source: 'Ki', privacy: 'Private', access: 'Source-relative view', recent: 5, saved: false, parts: ['Care Threshold Node', 'Invitation Signals', 'Receiver profile'], why: 'Receiver staging places three eligible Signals near this Locus.' },
  { id: 'systems-oracle', title: 'Systems Oracle', eyebrow: 'Connected technology map', description: 'Institutions, technologies, incentives, and relationships presented as a traversable graph.', layout: 'graph', realm: 'Knowledge & Frontier', source: 'Mapshifting', privacy: 'Public', access: 'Open', recent: 4, saved: true, parts: ['Systems Oracle Map', 'Authority Nodes', 'Research Seed'], image: 'assets/sigils/actions.png', why: 'It connects to current Agentic-interface research.' },
  { id: 'signals-film', title: 'How Signals Move', eyebrow: 'Media explainer', description: 'A focused audiovisual explanation of reception, bounded delivery, staging, and landing.', layout: 'theater', realm: 'Kiduna Commons', source: 'Moto', privacy: 'Public', access: 'Open', recent: 3, saved: false, parts: ['Transceiver Media', 'Landing diagrams', 'Public Seed'], why: 'Recently created Media related to the active Layout Kit.' },
  { id: 'future-commons', title: 'The Future Commons', eyebrow: 'Embodied 3D study', description: 'A walkable study of civic gathering, portals, shared resources, and public action.', layout: 'world', realm: 'Kiduna Commons', source: 'Commons Studio', privacy: 'Public', access: 'Rehearsal', recent: 2, saved: false, parts: ['Commons Realm', 'Civic Map', 'World Seed'], why: 'A Rehearsal is open to authorized participants.' },
  { id: 'field-notebook', title: 'Field Notes: Invitation as Orientation', eyebrow: 'Documentary essay', description: 'A reading-led collection of notes, diagrams, audio annotations, and sources.', layout: 'reader', realm: 'Moto’s Field', source: 'Moto', privacy: 'Personal', access: 'Source only', recent: 1, saved: true, parts: ['Field Notebook Seed', 'Kinship Map', 'Audio notes'], why: 'Saved in your personal working context.' },
  { id: 'royals-table', title: 'Royals & Rogues', eyebrow: 'Playable strategy Expression', description: 'A bounded social strategy game of position, risk, exchange, and shifting allegiance.', layout: 'game', realm: 'Culture & Play', source: 'Moto', privacy: 'Private', access: 'Rehearsal participants', recent: 8, saved: false, parts: ['Royals & Rogues Seed', 'Rules Map', 'Player Signals'], why: 'A playable Rehearsal is available in your current Field.' }
];

const workspaceMeta = {
  connector: ['Connector', 'Join Agents, Systems, and Realms without confusing connection with Authority.'],
  creator: ['Creator', 'Bring Meaning, Agents, Exchange, and Expressions into being.'],
  'inspector-workspace': ['Inspector', 'Search the objects, histories, evidence, boundaries, Actions, and receipts in Field.'],
  broker: ['Broker', 'Manage Resources, wallets, treasuries, exchange, and Sponsorships.'],
  envoy: ['Envoy', 'Govern, delegate, vote, and configure bounded decision activity.'],
  sentinel: ['Sentinel', 'Set Coherence, verification, security, privacy, and reception boundaries.']
};

function workspaceShell(id, eyebrow, content, tabs = '') {
  const [title, description] = workspaceMeta[id];
  return `<section class="tool-workspace tool-${id}" data-open-panel="${id}" aria-label="${title}"><div class="tool-atmosphere" aria-hidden="true"></div><header class="tool-workspace-header"><div><span>${escapeHtml(eyebrow)}</span><h1>${title}</h1><p>${escapeHtml(description)}</p></div><button class="tool-close" type="button" data-close-panel aria-label="Close ${title}">${icon('close', 20)}</button></header>${tabs}<div class="tool-workspace-scroll">${content}</div></section>`;
}

function legacyFieldExplorer(state) {
  const query = state.expressionQuery.toLowerCase();
  let items = expressions.filter(item => (!query || Object.values(item).flat().join(' ').toLowerCase().includes(query)) && (state.expressionLayout === 'All' || item.layout === state.expressionLayout) && (state.expressionRealm === 'All' || item.realm === state.expressionRealm) && (state.expressionSource === 'All' || item.source === state.expressionSource) && (state.expressionSeed === 'All' || item.parts.some(part => part === state.expressionSeed)) && (!state.expressionSavedOnly || item.saved));
  items.sort((a, b) => state.expressionSort === 'Oldest' ? a.recent - b.recent : state.expressionSort === 'Title' ? a.title.localeCompare(b.title) : b.recent - a.recent);
  const realms = ['All', ...new Set(expressions.map(item => item.realm))];
  const sources = ['All', ...new Set(expressions.map(item => item.source))];
  const seeds = ['All', ...new Set(expressions.flatMap(item => item.parts.filter(part => part.endsWith('Seed'))))];
  return `<section class="expression-explorer" aria-label="Expression explorer"><div class="expression-atmosphere" aria-hidden="true"></div><header><div><span>Field Canvas · proposed Layout Kit vocabulary</span><h1>Explore Expressions</h1><p>A complete piece present to you—composed from authorized Realms, Maps, Transmitters, Media, Nodes, and Seeds.</p></div><button class="expression-create" type="button" data-panel="creator">Create an Expression</button></header><section class="expression-controls"><label>${icon('search', 17)}<span class="sr-only">Search Expressions</span><input id="expression-search" type="search" value="${escapeHtml(state.expressionQuery)}" placeholder="Search Expressions, Realms, Maps, Transmitters, or Seeds…"></label><select id="expression-layout" aria-label="Filter by Layout"><option>All</option>${layoutTypes.map(type => `<option value="${type.id}" ${state.expressionLayout === type.id ? 'selected' : ''}>${type.name}</option>`).join('')}</select><select id="expression-realm" aria-label="Filter by Realm">${realms.map(realm => `<option ${state.expressionRealm === realm ? 'selected' : ''}>${escapeHtml(realm)}</option>`).join('')}</select><select id="expression-sort" aria-label="Sort Expressions"><option ${state.expressionSort === 'Most recent' ? 'selected' : ''}>Most recent</option><option ${state.expressionSort === 'Oldest' ? 'selected' : ''}>Oldest</option><option ${state.expressionSort === 'Title' ? 'selected' : ''}>Title</option></select><button class="${state.expressionSavedOnly ? 'active' : ''}" type="button" data-action="expression-saved">★ Saved</button></section><div class="expression-grid">${items.map(item => `<article class="expression-card layout-${item.layout}"><div class="expression-art">${item.image ? `<img src="${item.image}" alt="">` : `<span>${item.layout.slice(0,2)}</span>`}<i>${layoutTypes.find(type => type.id === item.layout)?.name}</i></div><div class="expression-copy"><span>${escapeHtml(item.eyebrow)}</span><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.description)}</p><dl><div><dt>Realm</dt><dd>${escapeHtml(item.realm)}</dd></div><div><dt>Source</dt><dd>${escapeHtml(item.source)}</dd></div><div><dt>Boundary</dt><dd>${escapeHtml(item.privacy)} · ${escapeHtml(item.access)}</dd></div></dl><small><b>Includes:</b> ${item.parts.map(escapeHtml).join(' · ')}</small><small><b>Why here:</b> ${escapeHtml(item.why)}</small></div><footer><button type="button" data-expression-favorite="${item.id}" aria-pressed="${item.saved}">${item.saved ? '★ Saved' : '☆ Save'}</button><button type="button" data-expression-inspect="${item.id}">Inspect</button><button class="primary" type="button" data-expression-open="${item.id}">Open Expression</button></footer></article>`).join('') || '<div class="tool-empty"><h2>No visible Expressions</h2><p>Adjust search or filters. Hidden material is not disclosed.</p></div>'}</div></section>`;
}

export function fieldExplorer(state) {
  const query = state.expressionQuery.toLowerCase();
  const realms = ['All', ...new Set(expressions.map(item => item.realm))];
  const sources = ['All', ...new Set(expressions.map(item => item.source))];
  const seeds = ['All', ...new Set(expressions.flatMap(item => item.parts.filter(part => part.includes('Seed'))))];
  let items = expressions.filter(item => {
    const searchable = Object.values(item).flat().join(' ').toLowerCase();
    return (!query || searchable.includes(query))
      && (state.expressionLayout === 'All' || item.layout === state.expressionLayout)
      && (state.expressionRealm === 'All' || item.realm === state.expressionRealm)
      && (state.expressionSource === 'All' || item.source === state.expressionSource)
      && (state.expressionSeed === 'All' || item.parts.includes(state.expressionSeed))
      && (!state.expressionSavedOnly || item.saved);
  });
  items.sort((a, b) => state.expressionSort === 'Oldest' ? a.recent - b.recent : state.expressionSort === 'Title' ? a.title.localeCompare(b.title) : b.recent - a.recent);
  const options = (values, selected) => values.map(value => `<option ${selected === value ? 'selected' : ''}>${escapeHtml(value)}</option>`).join('');
  return `<section class="expression-explorer" aria-label="Expression explorer"><div class="expression-atmosphere" aria-hidden="true"></div><header><div><span>Field Canvas · proposed Layout Kit vocabulary</span><h1>Explore Expressions</h1><p>A complete piece present to you—composed from authorized Realms, Maps, Transmitters, Media, Nodes, and Seeds.</p></div><button class="expression-create" type="button" data-panel="creator">Create an Expression</button></header><section class="expression-controls"><label>${icon('search',17)}<span class="sr-only">Search Expressions</span><input id="expression-search" type="search" value="${escapeHtml(state.expressionQuery)}" placeholder="Search Expressions, Realms, Maps, Transmitters, or Seeds…"></label><select id="expression-layout" aria-label="Filter by Layout"><option>All</option>${layoutTypes.map(type => `<option value="${type.id}" ${state.expressionLayout === type.id ? 'selected' : ''}>${type.name}</option>`).join('')}</select><select id="expression-realm" aria-label="Filter by Realm">${options(realms,state.expressionRealm)}</select><select id="expression-source" aria-label="Filter by Source or Transmitter">${options(sources,state.expressionSource)}</select><select id="expression-seed" aria-label="Filter by Seed">${options(seeds,state.expressionSeed)}</select><select id="expression-sort" aria-label="Sort Expressions">${options(['Most recent','Oldest','Title'],state.expressionSort)}</select><button class="${state.expressionSavedOnly ? 'active' : ''}" type="button" data-action="expression-saved">★ Saved</button></section><div class="expression-grid">${items.map(item => `<article class="expression-card layout-${item.layout}"><div class="expression-art">${item.image ? `<img src="${item.image}" alt="">` : `<span>${item.layout.slice(0,2)}</span>`}<i>${layoutTypes.find(type => type.id === item.layout)?.name}</i></div><div class="expression-copy"><span>${escapeHtml(item.eyebrow)}</span><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.description)}</p><dl><div><dt>Realm</dt><dd>${escapeHtml(item.realm)}</dd></div><div><dt>Source</dt><dd>${escapeHtml(item.source)}</dd></div><div><dt>Boundary</dt><dd>${escapeHtml(item.privacy)} · ${escapeHtml(item.access)}</dd></div></dl><small><b>Includes:</b> ${item.parts.map(escapeHtml).join(' · ')}</small><small><b>Why here:</b> ${escapeHtml(item.why)}</small></div><footer><button type="button" data-expression-favorite="${item.id}" aria-pressed="${item.saved}">${item.saved ? '★ Saved' : '☆ Save'}</button><button type="button" data-expression-inspect="${item.id}">Inspect</button><button class="primary" type="button" data-expression-open="${item.id}">Open Expression</button></footer></article>`).join('') || '<div class="tool-empty"><h2>No visible Expressions</h2><p>Adjust search or filters. Hidden material is not disclosed.</p></div>'}</div></section>`;
}

function connectorWorkspace(state) {
  const tab = state.connectorWorkspaceTab;
  const agents = [
    ['moto-avatar','Moto · Build Kiduna','Avatar','Represents Moto in Build Kiduna','Catalyst Role; representation only'],
    ['research-ally','Research Ally','Ally','Personal companion relationship','Draft and advise; revocable'],
    ['budget-actor','Budget Actor','Actor','Build Kiduna Realm operator','Receipts within weekly threshold'],
    ['alice-avatar','Alice','Avatar','Direct Source relationship','Visible relationship context only']
  ];
  const systems = [
    ['google','Google','Gmail · Meet · Calendar · YouTube'],['bluesky','Bluesky','Public social publishing'],['telegram','Telegram','Messaging and groups'],['solana','Solana','Wallet and settlement rail']
  ];
  const realms = [
    ['build','Build Kiduna','Member · Catalyst','Manage Roles'],['service','Service Alliance','Guest · invited','Request new Role'],['commons','Kiduna Commons','Not joined','Join']
  ];
  const connection = id => state.connectorConnections[id] || { connected: false, active: false, muted: false };
  let content = '';
  if (tab === 'Agents') content = `<div class="tool-card-grid">${agents.map(([id,name,type,relationship,authority]) => { const status = connection(id); return `<article class="tool-card"><span>${type} · ${status.connected ? 'Connected' : 'Disconnected'} · ${status.active ? 'Active' : 'Inactive'}</span><h2>${name}</h2><p>${relationship}</p><small>${authority}</small><div class="tool-actions"><button data-connection-action="${status.connected ? 'disconnect' : 'connect'}" data-connection-id="${id}">${status.connected ? 'Disconnect' : 'Connect'}</button><button data-connection-action="${status.active ? 'deactivate' : 'activate'}" data-connection-id="${id}" ${status.connected ? '' : 'disabled'}>${status.active ? 'Deactivate' : 'Activate'}</button><button data-connection-action="mute" data-connection-id="${id}">${status.muted ? 'Unmute' : 'Mute'}</button><button data-prototype-action="Chat with ${name}">Chat</button><button data-prototype-action="Inspect ${name}">Inspect</button></div></article>`; }).join('')}</div>`;
  if (tab === 'Systems') content = `<div class="tool-card-grid">${systems.map(([id,name,services]) => { const status = connection(id); return `<article class="tool-card"><span>System · ${status.connected ? 'Prototype connected' : 'Not connected'} · ${status.active ? 'Active' : 'Inactive'}</span><h2>${name}</h2><p>${services}</p><small>Last synchronization: ${status.connected ? 'Prototype state only · no live sync' : 'Never'}</small><div class="tool-actions"><button data-connection-action="${status.connected ? 'disconnect' : 'connect'}" data-connection-id="${id}">${status.connected ? 'Disconnect' : 'Connect'}</button><button data-connection-action="${status.active ? 'deactivate' : 'activate'}" data-connection-id="${id}" ${status.connected ? '' : 'disabled'}>${status.active ? 'Deactivate' : 'Activate'}</button><button data-prototype-action="Configure ${name}">Configure</button><button data-prototype-action="Review ${name} permissions">Permissions</button><button data-prototype-action="Inspect ${name}">Inspect</button></div></article>`; }).join('')}</div>`;
  if (tab === 'Realms') content = `<div class="tool-card-grid">${realms.map(([id,name,role,next]) => `<article class="tool-card"><span>Realm relationship</span><h2>${name}</h2><p>${role}</p><small>Joining, invitation, Role, Consent, and Authority remain distinct.</small><div class="tool-actions"><button data-prototype-action="${next} in ${name}">${next}</button>${id !== 'commons' ? `<button data-prototype-action="Leave ${name}">Leave</button>` : ''}<button data-prototype-action="Invite to ${name}">Invite</button><button data-prototype-action="Inspect ${name}">Inspect</button></div></article>`).join('')}<article class="tool-card invitation-codes"><span>Invitation codes</span><h2>Welcome paths</h2><p>Realm or Kiduna destination · Host context · optional Sponsorship, Coupon, or Gift.</p><small>Expiry, acceptance limit, remaining uses, audience, access proposal, revocation, and history remain inspectable.</small><div class="tool-actions"><button data-prototype-action="Create invitation code">Create code</button><button data-prototype-action="Manage invitation codes">Manage codes</button></div></article></div>`;
  const tabs = `<nav class="tool-tabs" aria-label="Connector sections">${['Agents','Systems','Realms'].map(item => `<button class="${tab === item ? 'active' : ''}" type="button" data-tool-tab="connectorWorkspaceTab" data-tool-tab-value="${item}">${item}</button>`).join('')}</nav>`;
  return workspaceShell('connector', 'Connections are scoped, inspectable, and revocable', content, tabs);
}

function creatorWorkspace(state) {
  const groups = [['Meaning',['Maps','Realms','Nodes','Media']],['Agents',['Avatars','Allies','Actors','Automations']],['Exchange',['Offers','Resources','Actions','DUNAs']],['Expressions',['Composed','Setting','Pulse','Graph','Theater','World','Reader','Game']]];
  const layouts = { composed:'Connected interface, Overlays, Panels, and Chrome.', setting:'Isometric room with depth and reusable spatial grammar.', pulse:'Layers, scatter, and viewport for many things in relation.', graph:'Cards and boxes joined by typed relationships.', theater:'Focused stage for watching and listening.', world:'Full 3D environment for embodied presence and movement.', reader:'Editorial flow for documents, books, magazines, audio, and video.', game:'Playable rules, choices, feedback, challenge, and shared or solo state.' };
  return workspaceShell('creator', 'Studio · proposed Layout Kit creation flow', `<div class="creator-groups">${groups.map(([group,items]) => `<section><span>${group}</span><div>${items.map(item => `<button type="button" data-create-kind="${item}">${item}</button>`).join('')}</div></section>`).join('')}</div><section class="creator-flow"><div><span>Expression draft</span><h2>Compose a complete piece</h2><p>Preview, Rehearsal, publication, and Live availability remain separate.</p></div><div class="creator-fields"><label>Name<input id="creator-name" value="${escapeHtml(state.creatorDraftName)}" placeholder="Untitled Expression"></label><label>Purpose<textarea id="creator-purpose" rows="3" placeholder="What should this Expression make possible?">${escapeHtml(state.creatorDraftPurpose)}</textarea></label><label>Privacy<select><option>Private</option><option>Public</option><option>Secret</option><option>Personal</option></select></label><label>Contributors<input placeholder="Moto, Allies, Realm contributors…"></label></div><div class="layout-example-grid">${layoutTypes.map(type => `<button class="layout-example ${state.creatorLayout === type.id ? 'selected' : ''}" type="button" data-creator-layout="${type.id}"><span>${type.name}</span><b>${escapeHtml(type.meta)}</b><p>${escapeHtml(layouts[type.id])}</p></button>`).join('')}</div><div class="creator-stage-actions"><button data-prototype-action="Preview Expression draft">Preview Draft</button><button data-prototype-action="Move Expression draft to Rehearsal">Prepare Rehearsal</button><button data-prototype-action="Review Expression publication">Publication review</button></div></section>`);
}

function inspectorWorkspace(state) {
  const records = [
    ['Signal','Alice invitation received','Alice → registered Receptor','Delivered to private Locus; not accepted or acted upon'],
    ['Action','Layout Site deployed','Moto · explicit instruction','Execution receipt preserved · production alias updated'],
    ['Record','Compute allocation receipt','Budget Actor','Verified provider receipt · Secret boundary'],
    ['Expression','Systems Oracle opened','Moto','Graph presentation; no new truth or Authority established'],
    ['Correction','Realm Role label corrected','Build Kiduna Governance','Prior Record superseded; history retained']
  ];
  const query = state.inspectorWorkspaceQuery.toLowerCase();
  return workspaceShell('inspector-workspace', 'Evidence before inference', `<section class="tool-filterbar"><label>${icon('search',16)}<input id="inspector-workspace-search" value="${escapeHtml(state.inspectorWorkspaceQuery)}" placeholder="Search objects, history, Sources, Realms, receipts…"></label><select><option>All object types</option><option>Signals</option><option>Actions</option><option>Records</option><option>Expressions</option></select><select><option>All Realms</option><option>Build Kiduna</option><option>Service Alliance</option></select><select><option>Any time</option><option>Today</option><option>Last 7 days</option><option>Custom range</option></select></section><div class="inspector-ledger">${records.filter(row => !query || row.join(' ').toLowerCase().includes(query)).map(([type,title,provenance,detail]) => `<article><span>${type}</span><h2>${title}</h2><p>${detail}</p><small><b>Provenance:</b> ${provenance}</small><div><button data-prototype-action="Inspect history for ${title}">History</button><button data-prototype-action="Inspect provenance for ${title}">Provenance</button><button data-prototype-action="Inspect boundaries for ${title}">Authority &amp; privacy</button></div></article>`).join('')}</div><aside class="distinction-strip"><b>Keep distinct</b><span>Object ≠ history</span><span>Proposal ≠ Action</span><span>Action ≠ receipt</span><span>Transmission ≠ delivery</span><span>Delivery Landing ≠ Semantic Landing</span><span>Visible ≠ verified</span></aside>`);
}

function brokerWorkspace(state) {
  const tab = state.brokerTab;
  const content = tab === 'Sponsorships' ? `<div class="tool-card-grid"><article class="tool-card feature"><span>Sponsorship · proposal</span><h2>Support the Welcome Path</h2><p>500 compute from Moto to Service Alliance for three invitation rehearsals.</p><small>Private · disclosure required · no promotional control · Realm approval pending</small><div class="tool-actions"><button data-prototype-action="Inspect Welcome Path sponsorship">Inspect terms</button><button data-prototype-action="Review Welcome Path sponsorship">Review proposal</button></div></article><article class="tool-card"><span>Gift · no reciprocal requirement</span><h2>Research Capacity Gift</h2><p>100 compute to Research Ally for evidence gathering.</p><small>Personal boundary · revocable before acceptance</small><div class="tool-actions"><button data-prototype-action="Inspect Research Capacity Gift">Inspect</button></div></article></div>` : `<div class="broker-metrics"><article><span>Personal Vault</span><strong>31,840</strong><small>Compute capacity</small></article><article><span>Build treasury</span><strong>4,820</strong><small>Themecoins</small></article><article><span>Pending approvals</span><strong>2</strong><small>No Resources moved</small></article><article><span>Receipts</span><strong>18</strong><small>1 failed · inspectable</small></article></div><div class="tool-card-grid"><article class="tool-card"><span>Offer</span><h2>Design review exchange</h2><p>Review two interface studies for 240 compute.</p><small>Draft Offer · no Commitment yet</small></article><article class="tool-card"><span>Realm treasury</span><h2>Service Alliance</h2><p>$7.2k held · 1 active allocation · 2 proposed Gifts.</p><small>Realm-governed view</small></article><article class="tool-card"><span>Resources</span><h2>Coupons, Gifts &amp; Rewards</h2><p>3 Coupons · 2 Gifts · 4 unclaimed Rewards.</p><small>Access and transferability vary</small></article></div>`;
  const tabs = `<nav class="tool-tabs" aria-label="Broker sections">${['Overview','Sponsorships','Offers','Treasuries','History'].map(item => `<button class="${tab === item ? 'active' : ''}" data-tool-tab="brokerTab" data-tool-tab-value="${item}">${item}</button>`).join('')}</nav>`;
  return workspaceShell('broker', 'Exchange must remain attributable and governed', content, tabs);
}

function envoyWorkspace(state) {
  return workspaceShell('envoy', 'Delegation does not create unlimited Authority', `<section class="tool-filterbar"><select id="envoy-realm"><option>All Realms</option><option>Build Kiduna</option><option>Service Alliance</option></select><button data-prototype-action="Configure Envoy mandate">Configure Envoy</button></section><div class="envoy-grid"><article class="governance-card urgent"><span>Vote · closes tomorrow</span><h2>Contribution recognition</h2><p>Direct Source vote · Build Kiduna</p><small>Current state: not cast · 62% participation</small><button data-prototype-action="Review Contribution recognition vote">Review vote</button></article><article class="governance-card"><span>Decision market · 3 days</span><h2>Release sequencing</h2><p>Envoy may allocate up to 180 compute under a revocable mandate.</p><small>Spent 40 / 180 · threshold 60 per position</small><button data-prototype-action="Inspect Release sequencing market">Inspect market</button></article><article class="governance-card"><span>Delegation</span><h2>Governance Envoy</h2><p>Build Kiduna only · proposals and votes · expires Sep 30.</p><small>Spend limit 200 · approval required above 60 · revocable now</small><div><button data-prototype-action="Revise Governance Envoy mandate">Revise</button><button data-prototype-action="Revoke Governance Envoy mandate">Revoke</button></div></article></div><section class="history-panel"><h2>Governance history</h2><p>Every direct vote and delegated Action retains actor, mandate, decision, outcome, and receipt.</p></section>`);
}

function sentinelWorkspace(state) {
  const boundaries = state.sentinelBoundaries;
  return workspaceShell('sentinel', 'Coherence without a universal score', `<div class="sentinel-columns"><section><span>Coherence &amp; Vibes</span><h2>Reception tolerances</h2><p>These Source-relative ranges affect staging and warnings. They do not rewrite underlying material.</p>${[['participation','Participation'],['stewardship','Stewardship'],['belonging','Belonging'],['legibility','Authority legibility']].map(([id,label]) => `<label class="sentinel-range"><span>${label}<output>${boundaries[id]}</output></span><input type="range" min="0" max="100" value="${boundaries[id]}" data-sentinel-range="${id}"></label>`).join('')}</section><section><span>Content boundaries</span><h2>What reaches you, and how</h2><p>Adults may choose Open where legally and technically permitted.</p><div class="boundary-presets">${['Guided','Balanced','Open'].map(item => `<button class="${state.sentinelPreset === item ? 'active' : ''}" data-sentinel-preset="${item}">${item}</button>`).join('')}</div>${['Age appropriateness','Violence','Trauma','Sexual content','Racial identity and topics','Harassment or abuse','Graphic material','Distressing subjects'].map(item => `<label class="boundary-row"><span>${item}</span><select data-boundary-topic="${item}"><option>Warn</option><option>Hold</option><option>Allow</option></select></label>`).join('')}</section><section><span>Verification &amp; trust</span><h2>Evidence stays attributable</h2><div class="sentinel-list"><button data-prototype-action="Open identity verification">Identity verification <b>2 current</b></button><button data-prototype-action="Open evidence review">Evidence review <b>4 pending</b></button><button data-prototype-action="Open peer verification">Peer verification <b>Contextual</b></button><button data-prototype-action="Open disputes and corrections">Disputes &amp; corrections <b>1 open</b></button><button data-prototype-action="Open verification history">Verification history <b>Inspect</b></button></div></section><section><span>Security &amp; privacy</span><h2>Boundaries and reasons</h2><div class="sentinel-list"><button data-prototype-action="Open visibility rules">Visibility rules <b>Personal / Private / Secret / Public</b></button><button data-prototype-action="Review held Signals">Held Signals <b>3 · reasons visible</b></button><button data-prototype-action="Review security alerts">Security alerts <b>1 attention</b></button><button data-prototype-action="Review permissions and Consent">Permissions &amp; Consent <b>Review</b></button><button data-prototype-action="Review retention">Data retention <b>4 policies</b></button></div></section></div>`);
}

export function workspaceFor(state) {
  if (state.openPanel === 'connector') return connectorWorkspace(state);
  if (state.openPanel === 'creator') return creatorWorkspace(state);
  if (state.openPanel === 'inspector-workspace') return inspectorWorkspace(state);
  if (state.openPanel === 'broker') return brokerWorkspace(state);
  if (state.openPanel === 'envoy') return envoyWorkspace(state);
  if (state.openPanel === 'sentinel') return sentinelWorkspace(state);
  return '';
}

export function expressionOverlay(state) {
  const item = expressions.find(expression => expression.id === state.activeExpressionId);
  if (!item) return '';
  return `<header class="active-expression-bar"><button type="button" data-action="close-expression">← Expressions</button><div><span>${layoutTypes.find(type => type.id === item.layout)?.name} Expression</span><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.realm)} · ${escapeHtml(item.privacy)}</small></div><button type="button" data-expression-inspect="${item.id}">Inspect</button></header>`;
}

export function expressionInspector(state) {
  const item = expressions.find(expression => expression.id === state.expressionInspectId);
  if (!item) return '';
  return `<aside class="expression-inspector" role="dialog" aria-label="Inspect ${escapeHtml(item.title)}"><header><div><span>Expression · read-only inspection</span><h2>${escapeHtml(item.title)}</h2></div><button type="button" data-action="close-expression-inspector" aria-label="Close Expression inspection">${icon('close',18)}</button></header><p>${escapeHtml(item.description)}</p><dl><div><dt>Layout</dt><dd>${layoutTypes.find(type => type.id === item.layout)?.name}</dd></div><div><dt>Realm</dt><dd>${escapeHtml(item.realm)}</dd></div><div><dt>Source / Transmitter</dt><dd>${escapeHtml(item.source)}</dd></div><div><dt>Privacy and access</dt><dd>${escapeHtml(item.privacy)} · ${escapeHtml(item.access)}</dd></div><div><dt>Included material</dt><dd>${item.parts.map(escapeHtml).join(' · ')}</dd></div><div><dt>Why visible</dt><dd>${escapeHtml(item.why)}</dd></div><div><dt>Provenance</dt><dd>Prototype Expression record; inspectable components retain their own identity and lineage.</dd></div></dl><small>Opening this Expression changes presentation only. It does not verify its content, widen access, or execute an Action.</small><button class="primary" type="button" data-expression-open="${item.id}">Open Expression</button></aside>`;
}

function actionDetail(action) {
  return `<small><b>Target:</b> ${escapeHtml(action.target)} · <b>Scope:</b> ${escapeHtml(action.scope)} · <b>Authority:</b> ${escapeHtml(action.authority)} · <b>Privacy:</b> ${escapeHtml(action.privacy)} · <b>Reversibility:</b> ${escapeHtml(action.reversibility)}</small>`;
}

export function universalKi(state) {
  const proposal = state.kiProposal;
  return `<section class="receiver-v2-ki universal-ki" aria-label="Work with Ki"><div class="ki-word-circle" aria-hidden="true">Ki</div><label><span>Ki · ${state.routeLabel}</span><input id="universal-ki-input" value="${escapeHtml(state.kiDraft)}" placeholder="Ask Ki to find, inspect, arrange, explain, or propose actions here…"></label><div class="receiver-v2-voice-actions"><button type="button" data-action="universal-dictate"><span class="interface-icon icon-microphone" aria-hidden="true"></span><span>Dictate</span></button><button type="button" data-action="universal-voice"><span class="interface-icon icon-voice-live" aria-hidden="true"></span><span>Voice</span></button><button class="receiver-v2-preview universal-preview" type="button" data-action="ki-preview">Preview actions</button></div>${proposal ? `<aside class="ki-action-review" role="dialog" aria-label="Review Ki’s proposed actions"><header><div><span>Review Ki’s proposed actions</span><h2>Nothing happens until you approve.</h2></div><button type="button" data-action="ki-cancel" aria-label="Close action review">${icon('close',18)}</button></header>${state.kiRevisionMode ? `<section class="ki-revise"><p>Tell Ki what to keep, remove, narrow, or change. The revised proposal will return for review and will not be applied.</p><textarea id="ki-revision-input" rows="3" placeholder="Revise the proposal…">${escapeHtml(state.kiRevisionDraft)}</textarea><div><button type="button" data-action="ki-revision-cancel">Back</button><button class="primary" type="button" data-action="ki-revision-preview">Preview revision</button></div></section>` : `<div class="ki-review-toolbar"><button type="button" data-action="ki-select-all">Select all</button><button type="button" data-action="ki-clear-all">Clear all</button><span>${state.kiSelectedActions.length} of ${proposal.actions.length} selected</span></div><div class="ki-action-list">${proposal.actions.map(action => `<label><input type="checkbox" data-ki-action-check="${action.id}" ${state.kiSelectedActions.includes(action.id) ? 'checked' : ''}><span><b>${escapeHtml(action.title)}</b><em>${escapeHtml(action.effect)}</em>${actionDetail(action)}<i>${action.classification}</i></span></label>`).join('')}</div><footer><button type="button" data-action="ki-revise">Revise</button><button type="button" data-action="ki-cancel">Cancel</button><button type="button" data-action="ki-approve-selected" ${state.kiSelectedActions.length ? '' : 'disabled'}>Approve selected</button><button class="primary" type="button" data-action="ki-approve-all">Approve all</button></footer>`}</aside>` : ''}</section>`;
}

export function proposeKiActions(state, revision = '') {
  const context = state.routeLabel;
  const text = (revision || state.kiDraft || '').trim();
  const base = [
    { id:'focus', title:`Refine the ${context} view`, effect:text ? `Use “${text}” to adjust the current local presentation.` : 'Bring the most relevant local material into the current view.', target:context, scope:'Current browser view', authority:'Moto · local presentation', privacy:'No visibility widening', reversibility:'Fully reversible', classification:'LOCAL · PRESENTATION' },
    { id:'inspect', title:'Open supporting detail', effect:'Stage provenance, boundaries, and reasons beside the selected material.', target:'Current selection', scope:'Inspector overlay', authority:'Read-only authorized view', privacy:'Existing access only', reversibility:'Close overlay', classification:'LOCAL · READ ONLY' },
    { id:'save', title:'Save this working arrangement', effect:'Persist the current filters and arrangement in this browser.', target:'Local Layout state', scope:'This device', authority:'Moto', privacy:'Local storage', reversibility:'Reset or change later', classification:'LOCAL · STATE CHANGE' }
  ];
  return { prompt: text, revision, actions: base };
}
